export type HostErrorCode =
    "UNINITIALIZED_STREAM" |
    "UNATTACHED_STREAMS" |
    "UNKNOWN_CHANNEL" |
    "LOG_NOT_AVAILABLE" |
    "SEQUENCE_IDENTIFICATION_FAILED" |
    "UNKNOWN_SEQUENCE" |
    "UNKNOWN_INSTANCE" |
    "EVENT_NAME_MISSING" |
    "CONTROLLER_ERROR" |
    "SOCKET_TAKEN" |
    "API_CONFIGURATION_ERROR" |
    "SEQUENCE_STARTUP_CONFIG_READ_ERROR" |
    "SEQUENCE_SELECTOR_CONFLICT" |
    "SEQUENCE_STARTUP_ERROR" |
    "SEQUENCE_IN_USE" |
    "SEQUENCE_EXISTS" |
    "CPM_CONFIGURATION_ERROR" |
    "HOST_OVERLOAD" |
    "INVALID_CONTENT_TYPE" |
    "INSTANCE_ID_CONFLICT" |
    "INSTANCE_NAME_CONFLICT" |
    "INSTANCE_STARTUP_ERROR" |
    "ERR_PLATFORM_REQUEST_ERROR" |
    "PLATFORM_CONNECTION_LOST"
;
