export enum RunnerExitCode {
    INVALID_ENV_VARS = 20,
    INVALID_SEQUENCE_PATH = 21,
    SEQUENCE_FAILED_ON_START = 22,
    SEQUENCE_FAILED_DURING_EXECUTION = 23,
    SEQUENCE_UNPACK_FAILED = 10
}
