apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: sth
  labels:
    app: sth
    app.kubernetes.io/name: sth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sth
      app.kubernetes.io/name: sth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sth
        app: sth
    spec:
      serviceAccountName: sth-sa
      automountServiceAccountToken: true
      containers:
      - name: sth
        image: scramjetorg/sth:0.18.0
        command: ["scramjet-transform-hub"]
        env:
        - name: DEVELOPMENT
          value: \"false\"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - "--runtime-adapter=kubernetes"
          - "--k8s-runner-image=scramjetorg/runner:0.18.0"
          - "--k8s-namespace=default"
          - "--k8s-sth-pod-host=sth-runner"
        ports:
        - name: sth-api
          containerPort: 8000
        - name: sth-runner
          containerPort: 8001
      restartPolicy: Always
