kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: sth-role
  labels:
    app.kubernetes.io/name: sth
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "create", "update", "delete", "list"]

  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "list", "get"]

  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get", "list"]

  - apiGroups: [""]
    resources: ["resourcequotas"]
    verbs: ["get", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: sth-rolebinding
  labels:
    app.kubernetes.io/name: sth
subjects:
  - kind: ServiceAccount
    name: sth-sa
roleRef:
  kind: Role
  name: sth-role
  apiGroup: rbac.authorization.k8s.io
