apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: sth-secret
  labels:
    app.kubernetes.io/name: sth
  annotations:
    kubernetes.io/service-account.name: sth-sa
type: kubernetes.io/service-account-token
