export type HostErrorCode =
    "UNINITIALIZED_STREAM" |
    "UNATTACHED_STREAMS" |
    "UNKNOWN_CHANNEL" |
    "LOG_NOT_AVAILABLE" |
    "UNKNOWN_SEQUENCE" |
    "UNKNOWN_INSTANCE" |
    "CONTROLLER_ERROR" |
    "API_CONFIGURATION_ERROR"
