export type RunnerErrorCode =
    "SEQUENCE_ENDED_PREMATURE" |
    "SEQUENCE_RUNTIME_ERROR" |
    "UNINITIALIZED_STREAMS" |
    "UNKNOWN_MESSAGE_CODE" |
    "NO_MONITORING" |
    "UNINITIALIZED_CONTEXT" |
    "NO_SEQUENCE_FOUND"
