export type SupervisorErrorCode =
    "INVALID_CONFIGURATION" | "UNINITIALIZED_STREAMS" |
    "GENERAL_ERROR" | "SEQUENCE_RUN_BEFORE_INIT" | "RUNNER_ERROR" |
    "RUNNER_NON_ZERO_EXITCODE" | "RUNNER_NOT_STARTED" | "DOCKER_ERROR" | "PRERUNNER_ERROR"
