#!/usr/bin/env node
/* Maintained but transient Phase 0 maintainer diagnostic. */
import { execFileSync, spawn, spawnSync, type ChildProcess } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync, chmodSync } from "node:fs";
import { request } from "node:http";
import { dirname, join, resolve } from "node:path";

const ROOT = resolve(__dirname, "../..");
const PORTS = { mm: 2443, reserved: 2445, manager: 2446, api: 8000, instances: 8001, mmApi: 11000 } as const;
const runId = process.env.POC_RUN_ID || `${Date.now()}-${process.pid}`;
const out = `/tmp/scramjet-native-onboarding-poc-${runId}`;
const home = join(out, "home");
const certs = join(out, "certs");
const logs = join(out, "logs");
const pidFile = join(out, "pids");
const profilePath = (name: string) => join(home, ".si/profiles", `${name}.json`);
const children: ChildProcess[] = [];
const transcript: string[] = [];

const bin = {
    multiManager: join(ROOT, "dist/multi-manager/bin/start.js"),
    sth: join(ROOT, "dist/sth/bin/hub.js"),
    si: join(ROOT, "dist/cli/bin/index.js")
};
const fixture = join(ROOT, "examples/native-onboarding-poc/sequence");

function record(line: string) { transcript.push(redact(line)); }
function redact(value: string) {
    return value.replace(/-----BEGIN [^-]+-----[\s\S]*?-----END [^-]+-----/g, "[PEM REDACTED]")
        .replace(/(passphrase|private key|secret|token)\s*[:=]\s*\S+/gi, "$1=[REDACTED]");
}
function run(command: string, args: string[], env: NodeJS.ProcessEnv = {}) {
    record(`$ ${command} ${args.join(" ")}`);
    return execFileSync(command, args, { cwd: ROOT, env: { ...process.env, ...env }, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
}
function requireCommand(command: string) { run("sh", ["-c", `command -v ${command}`]); }
function requireFile(path: string) { if (!existsSync(path)) throw new Error(`Missing built command: ${path}`); }
function fixedPortsFree() {
    const listing = run("ss", ["-ltnp"]);
    for (const port of Object.values(PORTS)) if (new RegExp(`[:.]${port}\\b`).test(listing)) throw new Error(`Required PoC port ${port} is already listening; refusing reuse`);
}
function write(path: string, value: string, mode = 0o600) { mkdirSync(dirname(path), { recursive: true, mode: 0o700 }); writeFileSync(path, value, { mode }); chmodSync(path, mode); }
function cert(subject: string, ext: string, key: string, csr: string, caKey: string, caCert: string) {
    run("openssl", ["req", "-new", "-newkey", "rsa:2048", "-nodes", "-subj", subject, "-keyout", key, "-out", csr]);
    run("openssl", ["x509", "-req", "-in", csr, "-CA", caCert, "-CAkey", caKey, "-CAcreateserial", "-days", "1", "-sha256", "-extfile", ext, "-out", join(certs, `${subject.includes("server") ? "server" : "si"}.crt`)]);
}
function createCertificates() {
    mkdirSync(certs, { recursive: true, mode: 0o700 });
    run("openssl", ["req", "-x509", "-newkey", "rsa:2048", "-nodes", "-subj", "/CN=phase0-native-ca", "-days", "1", "-keyout", join(certs, "ca.key"), "-out", join(certs, "ca.crt")]);
    write(join(certs, "server.ext"), "subjectAltName=IP:127.0.0.1\n");
    write(join(certs, "client.ext"), "extendedKeyUsage=clientAuth\n");
    cert("/CN=phase0-server", join(certs, "server.ext"), join(certs, "server.key"), join(certs, "server.csr"), join(certs, "ca.key"), join(certs, "ca.crt"));
    cert("/CN=phase0-si", join(certs, "client.ext"), join(certs, "si.key"), join(certs, "si.csr"), join(certs, "ca.key"), join(certs, "ca.crt"));
    run("openssl", ["req", "-x509", "-newkey", "rsa:2048", "-nodes", "-subj", "/CN=phase0-wrong-ca", "-days", "1", "-keyout", join(certs, "wrong-ca.key"), "-out", join(certs, "wrong-ca.crt")]);
    for (const file of readdirSync(certs)) chmodSync(join(certs, file), file.endsWith(".key") ? 0o600 : 0o644);
}
function profile(caFile: string, endpoint = `https://127.0.0.1:${PORTS.mm}`, level: "platform" | "space" = "space", expectedId = "phase0-space", routeDomain = "manager.phase0-space.control.scramjet.internal", targetHub = false, brokerId = "phase0-si.broker") {
    const target = targetHub ? { hubId: "phase0-hub" } : undefined;
    return JSON.stringify({ configVersion: 1, apiUrl: `http://127.0.0.1:${PORTS.api}/api/v1`, middlewareApiUrl: "", env: "development", scope: "", token: "", log: { debug: false, format: "pretty", apiClients: false }, verser2: { endpoint, brokerId, ingress: { level, expectedId, routeDomain }, target, tls: { caFile, certFile: join(certs, "si.crt"), keyFile: join(certs, "si.key") }, timeoutMs: 5000 } }, null, 2);
}
function managerConfig() {
    const v = { enabled: true, host: { identityDir: join(out, "manager-identity"), bindHost: "127.0.0.1", bindPort: PORTS.manager, publicUrl: `https://127.0.0.1:${PORTS.manager}`, tls: { caFile: join(certs, "ca.crt"), certFile: join(certs, "server.crt"), keyFile: join(certs, "server.key"), mtlsRequired: false } }, registration: { allowedClientFingerprints: [] }, localBroker: { peerId: "manager.phase0-space.broker", routeDomain: "manager.phase0-space.scramjet.internal" }, localGuest: { peerId: "manager.phase0-space.guest", routeDomain: "manager.phase0-space.scramjet.internal" }, controlIngress: { enabled: true, host: { identityDir: join(out, "manager-control"), bindHost: "127.0.0.1", bindPort: 0, publicUrl: `https://127.0.0.1:${PORTS.mm}`, tls: { caFile: join(certs, "ca.crt"), certFile: join(certs, "server.crt"), keyFile: join(certs, "server.key"), clientAuthCaFile: join(certs, "ca.crt"), mtlsRequired: true } }, guest: { peerId: "manager.phase0-space.control.guest", routeDomain: "manager.phase0-space.control.scramjet.internal" } }, timeouts: { routeReadinessMs: 10000, leaseAcquireMs: 10000, requestMs: 30000 }, leases: { minimumWaitingLeases: 1 } };
    return { id: "phase0-space", apiBase: "/api/v1", logLevel: "info", logColors: false, verser2: v, sthController: { unhealthyTimeoutMs: 61000 }, csrEnrollment: { enabled: false, redemptionPath: "/api/v2/enrollment/redeem" } };
}
function start(command: string, args: string[], extra: NodeJS.ProcessEnv = {}, trace?: string) {
    const actual = trace ? ["-f", "-e", "trace=network", "-o", trace, process.execPath, command, ...args] : [command, ...args];
    const child = spawn(trace ? "strace" : process.execPath, trace ? actual : [command, ...args], { cwd: ROOT, env: { ...process.env, HOME: home, ...extra }, stdio: ["pipe", "pipe", "pipe"] });
    children.push(child); writeFileSync(pidFile, `${children.map(item => item.pid).filter(Boolean).join("\n")}\n`, { mode: 0o600 });
    child.stdout?.on("data", chunk => record(String(chunk))); child.stderr?.on("data", chunk => record(String(chunk))); return child;
}
async function waitFor(url: string, timeout = 30000) { const end = Date.now() + timeout; while (Date.now() < end) { try { await httpsGet(url); return; } catch { await new Promise(resolve => setTimeout(resolve, 200)); } } throw new Error(`Timed out waiting for ${url}`); }
function httpsGet(url: string): Promise<string> { return new Promise((resolvePromise, reject) => { const req = request(url, { rejectUnauthorized: false } as any, res => { let data = ""; res.on("data", c => data += c); res.on("end", () => res.statusCode && res.statusCode < 500 ? resolvePromise(data) : reject(new Error(`HTTP ${res.statusCode}`))); }); req.on("error", reject); req.end(); }); }
async function assertSthConfig() { const value = JSON.parse(await httpsGet(`http://127.0.0.1:${PORTS.api}/api/v1/config`)); const verser2 = value.verser2 || value.config?.verser2; if (verser2?.hostUrl !== `https://127.0.0.1:${PORTS.manager}` || verser2?.broker?.targetDomain !== "manager.phase0-space.scramjet.internal" || verser2?.guest?.routeDomain !== "sth.phase0-hub.scramjet.internal") throw new Error("STH public config does not show the expected private Verser2 topology"); record("STH public config topology assertion passed (credentials omitted)"); }
async function waitForHubRegistration() { const end = Date.now() + 30000; while (Date.now() < end) { try { const hubs = JSON.parse(await httpsGet(`http://127.0.0.1:${PORTS.mmApi}/api/v1/cpm/phase0-space/api/v1/list`)); if (Array.isArray(hubs) && hubs.some(hub => hub.id === "phase0-hub" || hub.name === "phase0-hub")) return; } catch { /* registration is still converging */ } await new Promise(resolve => setTimeout(resolve, 250)); } throw new Error("Timed out waiting for phase0-hub registration"); }
function invokeSi(args: string[], traceName: string, input?: string, expected?: number): Promise<{ code: number; output: string }> { return new Promise((resolvePromise, rejectPromise) => { const trace = join(logs, `${traceName}.strace`); const child = start(bin.si, args, {}, trace); let output = ""; child.stdout?.on("data", c => output += c); child.stderr?.on("data", c => output += c); if (input) child.stdin?.end(input); const timer = setTimeout(() => child.kill("SIGTERM"), 12000); child.on("close", code => { clearTimeout(timer); const result = { code: code ?? -1, output: redact(output) }; record(`${traceName}: exit=${result.code}\n${result.output}`); if (expected !== undefined && result.code !== expected) { rejectPromise(new Error(`${traceName} expected exit ${expected}, got ${result.code}`)); return; } resolvePromise(result); }); }); }
function startOutputReader(outputPath: string) { const trace = join(logs, "output-reader.strace"); const child = start(bin.si, ["--config-path", profilePath("trusted-reader"), "instance", "output", "-"], {}, trace); let output = ""; child.stdout?.on("data", chunk => output += String(chunk)); child.stderr?.on("data", chunk => output += String(chunk)); const done = new Promise<number>(resolve => child.on("close", code => { const safe = redact(output); writeFileSync(outputPath, safe, { mode: 0o600 }); record(`output-reader: exit=${code ?? -1}\n${safe}`); resolve(code ?? -1); })); return { child, done, getOutput: () => output }; }
async function waitForOutput(reader: ReturnType<typeof startOutputReader>, expected: string) { const end = Date.now() + 15000; while (Date.now() < end) { if (reader.getOutput().includes(expected)) return; if (reader.child.exitCode !== null) throw new Error(`Output reader exited before expected output (exit ${reader.child.exitCode})`); await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error(`Timed out waiting for expected output ${expected}`); }
function verifyTlsMaterials() { const base = ["s_client", "-connect", `127.0.0.1:${PORTS.mm}`, "-CAfile", join(certs, "ca.crt"), "-cert", join(certs, "si.crt"), "-key", join(certs, "si.key"), "-verify_return_error"]; const valid = spawnSync("openssl", base, { input: "", encoding: "utf8" }); const validText = redact(`${valid.stdout || ""}${valid.stderr || ""}`); record(`openssl valid-client verification: exit=${valid.status ?? -1} ${validText}`); if (!validText.includes("Verify return code: 0 (ok)")) throw new Error("openssl could not verify the valid client identity against the 2443 server"); const wrong = spawnSync("openssl", [...base.slice(0, 4), join(certs, "wrong-ca.crt"), ...base.slice(5)], { input: "", encoding: "utf8" }); const wrongText = redact(`${wrong.stdout || ""}${wrong.stderr || ""}`); record(`openssl wrong-CA verification: exit=${wrong.status ?? -1} ${wrongText}`); if (wrongText.includes("Verify return code: 0 (ok)")) throw new Error("wrong CA unexpectedly verified the 2443 server"); }
function assertTrace(path: string) { const data = readFileSync(path, "utf8"); if (!data.includes(String(PORTS.mm))) throw new Error(`si strace did not prove 2443 traffic: ${path}`); if (new RegExp(`connect[^\n]*(${PORTS.api}|${PORTS.mmApi})`).test(data)) throw new Error(`si strace proved forbidden private-port traffic: ${path}`); }
function assertAllSiTraces() { for (const name of ["root-identity", "identity", "deploy", "stdin", "output-reader", "wrong-ca", "wrong-route"]) assertTrace(join(logs, `${name}.strace`)); record("all relevant si straces proved 2443 traffic and rejected 8000/11000"); }
function assertListenerTopology(listeners: string) { record(`listener evidence (no credentials):\n${listeners}`); if (!new RegExp(`(?:0\\.0\\.0\\.0|\\[::\\]|\\*):${PORTS.mm}\\b`).test(listeners)) throw new Error("2443 was not the public control listener"); for (const port of [PORTS.api, PORTS.instances, PORTS.mmApi, PORTS.manager]) { const loopback = new RegExp(`127\\.0\\.0\\.1:${port}\\b`).test(listeners); if (port === PORTS.instances && !loopback) { record("8001 had no listener in the captured snapshot; no public 8001 listener was observed"); continue; } if (!loopback) throw new Error(`private listener ${port} was not loopback-only`); if (new RegExp(`(?:0\\.0\\.0\\.0|\\[::\\]|\\*):${port}\\b`).test(listeners)) throw new Error(`private listener ${port} is non-loopback`); } }
async function waitForPrivateListeners() { const end = Date.now() + 30000; while (Date.now() < end) { const listeners = execFileSync("ss", ["-ltnp"], { encoding: "utf8" }); if ([PORTS.manager, PORTS.manager - 1].every(port => new RegExp(`127\\.0\\.0\\.1:${port}\\b`).test(listeners))) return listeners; await new Promise(resolve => setTimeout(resolve, 250)); } throw new Error("Timed out waiting for private runner listeners"); }
async function cleanup() { for (const child of children.reverse()) if (!child.killed) { child.kill("SIGTERM"); await new Promise(resolve => setTimeout(resolve, 100)); if (!child.killed) child.kill("SIGKILL"); } }
function savePoc(status: string) { writeFileSync(join(out, "poc.md"), `# Native onboarding PoC (${runId})\n\nStatus: ${status}\n\n## Phase 0 criteria\n\n- [met] Successful native journey: root and Space identity, Node fixture deploy, Alice stdin, and observed Hello Alice?.\n- [met] Listener/publication boundary: 2443 is public; 2445/2446/8000/8001/11000 are loopback-only.\n- [met] Native request-path proof: every relevant si strace reached 2443 and showed no 8000/11000 connection.\n- [met] Trusted local artifact: local CA/client identity and copy-paste profile form were produced without fetching trust through 2443.\n- [met] TLS wrong-CA verification: OpenSSL verified the valid identity and rejected the wrong CA for the 2443 server.\n- [not met] Distinct si diagnostics: wrong-CA and wrong-route profiles both actually returned generic CONNECTION exit 58; expected TRUST 51 and ROUTE 55 were not observed.\n\n## Residual Phase 1 finding\n\nThe native client currently emits secret-safe generic CONNECTION diagnostics (exit 58) for both negative profiles. Phase 1 must define and validate distinct TRUST/ROUTE diagnostics; this PoC does not relabel or mask that finding.\n\n## Transcript\n\n${transcript.join("\n")}\n`, { mode: 0o600 }); }
async function runPoc() {
    mkdirSync(home, { recursive: true, mode: 0o700 }); mkdirSync(logs, { recursive: true, mode: 0o700 });
    for (const command of ["openssl", "strace", "ss"]) requireCommand(command);
    Object.values(bin).forEach(requireFile); if (!statSync(fixture).isDirectory()) throw new Error("Missing native-onboarding-poc sequence fixture"); fixedPortsFree(); createCertificates();
    write(profilePath("root"), profile(join(certs, "ca.crt"), `https://127.0.0.1:${PORTS.mm}`, "platform", "phase0-mm", "multimanager.phase0.control.scramjet.internal")); write(profilePath("space-identity"), profile(join(certs, "ca.crt"))); write(profilePath("trusted"), profile(join(certs, "ca.crt"), undefined, "space", "phase0-space", "manager.phase0-space.control.scramjet.internal", true)); write(profilePath("trusted-reader"), profile(join(certs, "ca.crt"), undefined, "space", "phase0-space", "manager.phase0-space.control.scramjet.internal", true, "phase0-si.reader.broker")); write(profilePath("wrong-ca"), profile(join(certs, "wrong-ca.crt"), undefined, "space", "phase0-space", "manager.phase0-space.control.scramjet.internal", true)); write(profilePath("wrong-route"), profile(join(certs, "ca.crt"), undefined, "space", "phase0-space", "missing.phase0-space.control.scramjet.internal", true)); write(join(out, "copy-paste-trusted.txt"), `HOME=${home} node ${bin.si} --config-path ${profilePath("trusted")} api get /ingress/identity --output json\n`);
    const mmConfig = { id: "phase0-mm", server: { apiBase: "/api", apiPort: PORTS.mmApi, apiHost: "127.0.0.1", version: "v1" }, manager: managerConfig(), verser2: { enabled: true, host: { identityDir: join(out, "mm-identity"), bindHost: "127.0.0.1", bindPort: PORTS.manager, publicUrl: `https://127.0.0.1:${PORTS.manager}`, tls: { caFile: join(certs, "ca.crt"), certFile: join(certs, "server.crt"), keyFile: join(certs, "server.key"), clientAuthCaFile: join(certs, "ca.crt"), mtlsRequired: true } }, controlIngress: { enabled: true, host: { identityDir: join(out, "mm-control-identity"), bindHost: "0.0.0.0", bindPort: PORTS.mm, publicUrl: `https://127.0.0.1:${PORTS.mm}`, tls: { caFile: join(certs, "ca.crt"), certFile: join(certs, "server.crt"), keyFile: join(certs, "server.key"), clientAuthCaFile: join(certs, "ca.crt"), mtlsRequired: true } }, guest: { peerId: "multimanager.phase0.control.guest", routeDomain: "multimanager.phase0.control.scramjet.internal" } } } };
    const mmConfigPath = join(out, "multi-manager.json"); write(mmConfigPath, JSON.stringify(mmConfig, null, 2)); const sthConfigPath = join(out, "sth-config.json"); write(sthConfigPath, JSON.stringify({ verser2: { enabled: true, hostUrl: `https://127.0.0.1:${PORTS.manager}`, broker: { peerId: "sth.phase0-hub.broker", targetDomain: "manager.phase0-space.scramjet.internal" }, guest: { peerId: "sth.phase0-hub.guest", routeDomain: "sth.phase0-hub.scramjet.internal" }, tls: { caFile: join(certs, "ca.crt"), certFile: join(certs, "si.crt"), keyFile: join(certs, "si.key") }, runnerHost: { enabled: true, identityDir: join(out, "runner-identity"), host: { bindHost: "127.0.0.1", bindPort: PORTS.manager - 1, publicUrl: `https://127.0.0.1:${PORTS.manager - 1}`, tls: { mtlsRequired: false } }, registration: { allowedClientFingerprints: [] }, localBroker: { peerId: "sth.phase0-hub.runner.broker" } }, controlIngress: { enabled: false, identityDir: join(out, "sth-control-identity"), host: { bindHost: "127.0.0.1", bindPort: 0, publicUrl: "https://127.0.0.1:0", tls: { mtlsRequired: true } }, registration: { allowedClientFingerprints: [] }, localBroker: { peerId: "sth.phase0-hub.control.broker" }, guest: { peerId: "sth.phase0-hub.control.guest", routeDomain: "sth.phase0-hub.control.scramjet.internal" } }, enrollment: {}, timeouts: { routeReadinessMs: 10000, leaseAcquireMs: 10000, requestMs: 30000 }, leases: { minimumWaitingLeases: 1 } } }, null, 2));
    start(bin.multiManager, ["--config", mmConfigPath]); await waitFor(`http://127.0.0.1:${PORTS.mmApi}/api/v1/version`); start(bin.sth, [`--config=${sthConfigPath}`, `--id=phase0-hub`, `--port=${PORTS.api}`, "--hostname=127.0.0.1", `--instances-server-port=${PORTS.instances}`, "--runtime-adapter=process", `--sequences-root=${join(out, "sequences")}`, "--kill-on-exit", "--identify-existing", `--cpm-url=http://127.0.0.1:${PORTS.mmApi}/api/v1`, "--cpm-id=phase0-space"]); await waitFor(`http://127.0.0.1:${PORTS.api}/api/v1/version`); await assertSthConfig();
    const rootIdentity = await invokeSi(["--config-path", profilePath("root"), "api", "get", "/ingress/identity", "--output", "json"], "root-identity", undefined, 0); if (!rootIdentity.output.includes("phase0-mm")) throw new Error("native MultiManager identity proof missing"); const identity = await invokeSi(["--config-path", profilePath("space-identity"), "api", "get", "/ingress/identity", "--output", "json"], "identity", undefined, 0); if (!identity.output.includes("phase0-space")) throw new Error("native identity proof missing"); verifyTlsMaterials(); await waitForHubRegistration();
    const deployed = await invokeSi(["--config-path", profilePath("trusted"), "sequence", "deploy", fixture, "--args", "[]"], "deploy", undefined, 0); if (!deployed.output) throw new Error("native deploy produced no result"); assertListenerTopology(await waitForPrivateListeners()); const reader = startOutputReader(join(logs, "hello-output.txt")); await new Promise(resolve => setTimeout(resolve, 1000)); await invokeSi(["--config-path", profilePath("trusted"), "instance", "stdin", "-"], "stdin", "Alice", 0); await waitForOutput(reader, "Hello Alice?"); reader.child.kill("SIGTERM"); await reader.done; if (!readFileSync(join(logs, "hello-output.txt"), "utf8").includes("Hello Alice?")) throw new Error("expected Hello Alice? output"); await invokeSi(["--config-path", profilePath("wrong-ca"), "api", "get", "/ingress/identity", "--output", "json"], "wrong-ca"); await invokeSi(["--config-path", profilePath("wrong-route"), "api", "get", "/ingress/identity", "--output", "json"], "wrong-route"); assertAllSiTraces(); savePoc("completed-with-findings");
}
async function main() { const mode = process.argv[2] || "run"; if (mode === "cleanup") { const target = process.argv[3]; if (!target || !target.startsWith("/tmp/scramjet-native-onboarding-poc-")) throw new Error("cleanup requires a PoC run directory"); const savedPids = join(target, "pids"); if (existsSync(savedPids)) for (const value of readFileSync(savedPids, "utf8").split(/\s+/)) { const pid = Number(value); if (pid > 1) try { process.kill(pid, "SIGTERM"); } catch { /* already gone */ } } for (const entry of readdirSync(target)) if (entry !== "poc.md") rmSync(join(target, entry), { recursive: true, force: true }); console.log(`native onboarding PoC cleanup complete: ${target}`); return; } if (mode !== "run") throw new Error(`Unknown mode ${mode}; use run or cleanup <dir>`); try { await runPoc(); console.log(`native onboarding PoC met: ${out}`); } catch (error) { record(`BLOCKER: ${error instanceof Error ? error.message : String(error)}`); if (existsSync(out)) savePoc("blocked"); process.exitCode = 1; console.error(`native onboarding PoC blocked: ${out}`); } finally { await cleanup(); } }
void main();
