apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kube-apiserver
  labels:
    app.kubernetes.io/name: {{ include "sth.name" . }}
    helm.sh/chart: {{ include "sth.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  egress:
    - to:
        - podSelector:
            matchLabels:
              component: kube-apiserver
      ports:
        - port: 6443
          protocol: TCP
  podSelector:
    matchLabels:
       app: sth
  policyTypes:
  - Egress
