{{- if .Values.serviceAccountToken.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sth-sa
  labels:
    app.kubernetes.io/name: {{ include "sth.name" . }}
    helm.sh/chart: {{ include "sth.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
secrets:
- name: sth-secret
{{- end }}
