{{- if .Values.serviceAccountToken.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sth-rolebinding
  labels:
    app.kubernetes.io/name: {{ include "sth.name" . }}
    helm.sh/chart: {{ include "sth.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: sth-sa
roleRef:
  kind: Role
  name: sth-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
