{{- if .Values.serviceAccountToken.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: sth-secret
  labels:
    app.kubernetes.io/name: {{ include "sth.name" . }}
    helm.sh/chart: {{ include "sth.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/service-account.name: sth-sa
type: kubernetes.io/service-account-token
{{- end }}
