{{- if .Values.sthApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: sth
  labels:
    app.kubernetes.io/name: {{ include "sth.name" . }}
    helm.sh/chart: {{ include "sth.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    service: sth
spec:
  type: {{ .Values.sthApi.service.type }}
  ports:
  - port: {{ .Values.sthApi.service.port }}
    name: sth
    targetPort: sth-api
    {{- if (eq .Values.sthApi.service.type "NodePort") }}
    nodePort: {{ .Values.sthApi.service.port }}
    {{- end }}
  {{- if or (eq .Values.sthApi.service.type "LoadBalancer") (eq .Values.sthApi.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.sthApi.service.externalTrafficPolicy }}
  {{- end }}
  selector:
    app: sth
{{- end }}
