{{- if .Values.serviceAccountToken.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sth-role
  labels:
    app.kubernetes.io/name: {{ include "sth.name" . }}
    helm.sh/chart: {{ include "sth.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "create", "update", "delete", "list"]

  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "list", "get"]

  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get", "list"]
{{- end }}
