kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: sth-policy
  labels:
    app.kubernetes.io/name: {{ include "sth.name" . }}
    helm.sh/chart: {{ include "sth.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
       app: sth
  ingress:
 {{- if (eq .Values.sthRunner.service.type "ClusterIP") }}
    - from:
        - podSelector:
            matchLabels:
              app: runner
      ports:
        - port: {{ .Values.sthRunner.service.port }}
  {{- end }}
    - ports:
  {{- if or (eq .Values.sthApi.service.type "LoadBalancer") (eq .Values.sthApi.service.type "NodePort") }}
        - port: {{ .Values.sthApi.service.port }}
    {{- end }}
  {{- if or (eq .Values.sthRunner.service.type "LoadBalancer") (eq .Values.sthRunner.service.type "NodePort") }}
        - port: {{ .Values.sthRunner.service.port }}
    {{- end }}
  egress:
  - {}
  policyTypes:
    - Ingress
    - Egress
