pipeline {
  agent {
    node {
      label 'scp'
    }
  }
  environment {
      docker_ci_image = 'repo.int.scp.ovh/scramjet/nodejs-ci:buster'
      docker_host_sock_gid = sh(returnStdout: true, script: 'stat -c %g /var/run/docker.sock').trim()
      // https://stackoverflow.com/questions/62282418/jenkins-sh-npm-i-not-working-in-docker-agent
      HOME = '.'
      SCRAMJET_TEST_LOG = 1
      docker_repo = 'repo.int.scp.ovh'
      version = sh(returnStdout: true, script: "jq -r .version < package.json").trim()
  }
  stages {
    stage('Checkout SCM') {
      steps {
        checkout scm
      }
    }
    stage('Install packages') {
      steps {
        script {
          docker.image("${docker_ci_image}").inside("-v /tmp/:/tmp") {
            sh('yarn install --prefer-offline --cache-folder /tmp/.cache_yarn-scramjet-csi')
          }
        }
      }
    }
    stage('Run Linter') {
      steps {
        script {
          docker.image("${docker_ci_image}").inside("-v /tmp:/tmp") {
            sh('yarn lint || yarn lint:uncached')
          }
        }
      }
    }
    stage('Build') {
      failFast true
      parallel {
        stage('Build packages') {
          steps {
            script {
              docker.image("${docker_ci_image}").inside() {
                sh('yarn build:packages')
              }
            }
          }
        }
        stage('Pack sequences') {
          steps {
            script {
              docker.image("${docker_ci_image}").inside() {
                sh('yarn build:refapps')
                sh('yarn packseq')
              }
            }
          }
        }
        stage('Build - Docker - Host') {
          steps {
            script {
              docker.build("${docker_repo}/scramjet/host:${version}", "-f packages/sth/Dockerfile .")
            }
          }
        }
        stage('Build - Docker - Pre-Runner') {
          steps {
            script {
              dir("packages/pre-runner") {
                docker.build("${docker_repo}/scramjet/pre-runner:${version}")
              }
            }
          }
        }
        stage('Build - Docker - Runner') {
          steps {
            script {
              docker.build("${docker_repo}/scramjet/runner:${version}", "-f packages/runner/Dockerfile .")
            }
          }
        }
      }
    }
    stage('Run Tests') {
      failFast false
      parallel {
        stage('TS') {
          steps {
            script {
              docker.image("${docker_ci_image}").inside() {
                sh('yarn test:packages')
              }
            }
          }
        }
        stage('BDD') {
          options {
            timeout(time: 600, unit: 'SECONDS') // 10 minutes!
          }
          steps {
            script {
              docker.image("${docker_ci_image}").inside("--network=host --group-add=${docker_host_sock_gid} -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp") {
                sh('yarn test:bdd-ci')
              }
            }
          }
        }
      }
    }
  }
  post {
    always {
      // When successed currentBuild.result is null
      script {
        if (currentBuild.result == null) {
          currentBuild.result = 'SUCCESS'
        }
      }
      echo 'Cleaning..'
      cleanWs()
    }
    // Slack Notifications syntax: https://www.jenkins.io/doc/pipeline/steps/slack/
    unsuccessful {
      script {
        // CHANGE_ID is set only for pull requests
        if (env.CHANGE_ID) {
          slackSend (color: '#FF0000', message: "Job ${env.JOB_NAME} [${env.BUILD_NUMBER}] (${env.BUILD_URL}) failed.")
        }
      }
    }
    fixed {
      script {
        // CHANGE_ID is set only for pull requests
        if (env.CHANGE_ID) {
          slackSend (color: '#00FF00', message: "Job ${env.JOB_NAME} [${env.BUILD_NUMBER}] (${env.BUILD_URL}) back to normal.")
        }
      }
    }
  }
}

