/**
 * Integration coverage for the dist workspace generated by build-all.js.
 */

"use strict";

const test = require("ava").default;
const { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } = require("node:fs");
const { tmpdir } = require("node:os");
const { join, resolve } = require("node:path");
const { spawnSync } = require("node:child_process");

const buildAll = resolve(__dirname, "..", "build-all.js");
const prePack = resolve(__dirname, "..", "lib", "pre-pack.js");
const rootPackage = resolve(__dirname, "..", "..", "package.json");

function createWorkspace(t) {
	const root = mkdtempSync(join(tmpdir(), "transform-hub-build-all-"));

	writeFileSync(join(root, "package.json"), JSON.stringify({
		name: "build-all-fixture-root",
		private: true,
		workspaces: { packages: ["packages/*"] }
	}));

	for (const [directory, name] of [
		["utility", "@scramjet/utility"],
		["verser", "@scramjet/verser"]
	]) {
		const packageDir = join(root, "packages", directory);
		mkdirSync(packageDir, { recursive: true });
		writeFileSync(join(packageDir, "package.json"), JSON.stringify({ name, version: "1.0.0" }));
	}

	t.teardown(() => rmSync(root, { force: true, recursive: true }));
	return root;
}

test("build-all limits dist workspace installation to release-boundary packages", (t) => {
	const root = createWorkspace(t);
	const result = spawnSync(process.execPath, [
		buildAll,
		"--root", root,
		"--workspace", "packages",
		"--no-build",
		"--no-install"
	], { encoding: "utf8" });

	t.is(result.status, 0, result.stderr);
	const distPackage = JSON.parse(readFileSync(join(root, "dist", "package.json"), "utf8"));
	t.deepEqual(distPackage.workspaces, ["utility"]);
	t.true(existsSync(join(root, "dist", "verser", "package.json")));
});

test("build scripts use the repository npm through unversioned npx", (t) => {
	const buildAllSource = readFileSync(buildAll, "utf8");
	const prePackSource = readFileSync(prePack, "utf8");

	for (const source of [buildAllSource, prePackSource]) {
		t.true(source.includes("npx npm install"));
		t.false(source.includes("npx npm@"));
	}
});

test("root build handoffs use the repository npm binary", (t) => {
	const scripts = JSON.parse(readFileSync(rootPackage, "utf8")).scripts;

	t.true(scripts.build.startsWith("./node_modules/.bin/npm run build:all"));
	t.true(scripts["build:all"].includes("./node_modules/.bin/npm run build:packages"));
	t.true(scripts["build:all"].includes("./node_modules/.bin/npm run build:docker"));
	t.true(scripts["build:docker"].startsWith("./node_modules/.bin/npm run build:docker:stage-runner"));
});
