name: STH build and tests Node.js 16.x

on:
  pull_request:
    branches: [ release/*, main, devel ]

jobs:
  analyze-code:
    uses: ./.github/workflows/analyze-code.yml
    with:
      node-version: 16.x

  build-sth:
    uses: ./.github/workflows/build-sth.yml
    with:
      node-version: 16.x

  build-refapps:
    uses: ./.github/workflows/build-refapps.yml
    with:
      node-version: 16.x

  build-docker-sth-image:
    needs: [analyze-code, build-sth]
    uses: ./.github/workflows/build-docker-sth.yml
    with:
      node-version: 16.x

  build-docker-runner-image:
    uses: ./.github/workflows/build-docker-runner-node.yml
    with:
      node-version: 16.x

  build-docker-runner-py-image:
    uses: ./.github/workflows/build-docker-runner-python.yml
    with:
      node-version: 16.x

  build-docker-pre-runner-image:
    uses: ./.github/workflows/build-docker-prerunner.yml
    with:
      node-version: 16.x

  test-sth-unit:
    needs: [build-sth]
    uses: ./.github/workflows/test-unit.yml
    with:
      node-version: 16.x

  test-bdd-hub:
    needs: [build-sth, build-refapps, build-docker-runner-image, build-docker-runner-py-image, build-docker-pre-runner-image]
    uses: ./.github/workflows/test-bdd-process.yml
    with:
      test-title: STH command line test
      node-version: 16.x
      test-name: test:bdd-ci-hub-process

  test-bdd-ci-sth-api:
    needs: [build-sth, build-refapps, build-docker-runner-image, build-docker-runner-py-image, build-docker-pre-runner-image]
    uses: ./.github/workflows/test-bdd-process.yml
    with:
      test-title: STH API tests
      node-version: 16.x
      test-name: test:bdd-ci-api

  test-bdd-ci-sth-process-python:
    needs: [build-sth, build-refapps, build-docker-runner-image, build-docker-runner-py-image, build-docker-pre-runner-image]
    uses: ./.github/workflows/test-bdd-process.yml
    with:
      test-title: STH Python Sequences Test
      node-version: 16.x
      test-name: test:bdd-ci-python

  test-bdd-ci-sth-process-node:
    needs: [build-sth, build-refapps]
    uses: ./.github/workflows/test-bdd-process.yml
    with:
      test-title: STH Node.js Sequences Test
      node-version: 16.x
      test-name: test:bdd-ci-node

  test-bdd-ci-sth-docker-python:
    needs: [build-sth, build-refapps, build-docker-runner-image, build-docker-runner-py-image, build-docker-pre-runner-image]
    uses: ./.github/workflows/test-bdd-docker.yml
    with:
      test-title: STH Python Sequences Test
      node-version: 16.x
      test-name: test:bdd-ci-python

  test-bdd-ci-sth-docker-node:
    needs: [build-sth, build-refapps]
    uses: ./.github/workflows/test-bdd-docker.yml
    with:
      test-title: STH Node.js Sequences Test
      node-version: 16.x
      test-name: test:bdd-ci-node

  # trigger-compatibility-test:
  #   name: STH-CPM compatibility test (from platform-tests)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: convictional/trigger-workflow-and-wait@v1.6.1
  #       with:
  #         owner: scramjetorg
  #         repo: platform-tests
  #         github_token: ${{ secrets.SCRAMJET_BOT_TOKEN }}
  #         github_user: ${{ secrets.WORKFLOW_TRIGGER_USERNAME }}
  #         workflow_file_name: compatibility-check.yml
  #         client_payload: |
  #           {
  #             "sth-version": "${{ github.event.pull_request.head.sha }}"
  #           }
