name: Analyze Source Code

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        default: '16.x'
        type: string


jobs:
  analyze-code:
    name: Analyze the source code

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - name: Setup Nodejs ${{ inputs.node-version }}
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node-version }}

      - name: ls cache
        run: echo "${$( yarn cache dir )}" && find $( yarn cache dir ) -max_depth 2 -type d

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline --silent

      - name: Run Linter
        run: yarn lint
