name: Reusable workflow example

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        default: '16.x'
        type: string

jobs:
  build-refapps:
    name: Build Reference Apps Nodejs ${{ inputs.node-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - name: Setup Nodejs ${{ inputs.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: yarn install --ignore-engines  --frozen-lockfile --silent

      - name: Build refapps
        run: yarn build:refapps

      - name: Create artifact
        run: tar --use-compress-program="pigz -0 --recursive" -cvf dist-refapps-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz packages/reference-apps/*.tar.gz python/reference-apps/*.tar.gz

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-refapps-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz
          path: dist-refapps-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz
          retention-days: 1
