name: Reusable workflow example

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  build-sth:
    name: Build STH Packages Nodejs ${{ inputs.node-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - name: Setup Nodejs ${{ inputs.node-version }}
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --silent

      - name: Build packages
        run: yarn build:packages

      - name: Run packages tests
        run: yarn test:packages-no-concurrent

      - name: Create artifact
        run: tar --exclude=dist-sth-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz --use-compress-program="pigz --best --recursive" -cf dist-sth-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz dist/

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-sth-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz
          path: dist-sth-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz
          retention-days: 1

