name: Reusable workflow example

on: workflow_call

jobs:
  build-sth:
    name: Build Reference Apps Nodejs ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      fail-fast: true
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline --silent

      - name: Build packages
        run: yarn build:packages

      - name: Run packages tests
        run: yarn test:packages-no-concurrent

      - name: Create artifact
        run: tar --exclude=dist-sth-${{ github.event.pull_request.head.sha }}-${{ matrix.node-version }}.tar.gz --use-compress-program="pigz --best --recursive" -cf dist-sth-${{ github.event.pull_request.head.sha }}-${{ matrix.node-version }}.tar.gz dist/

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-sth-${{ github.event.pull_request.head.sha }}-${{ matrix.node-version }}.tar.gz
          path: dist-sth-${{ github.event.pull_request.head.sha }}-${{ matrix.node-version }}.tar.gz
          retention-days: 1

