name: Build Runner Docker Image Python

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        default: '3.9'
        type: string
      git-revision:
        required: false
        default: ${{ github.sha }}
        type: string

jobs:
  build-docker-runner-python-image:
    name: Build runner-py docker image (Python ${{ inputs.python-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git-revision }}

      - name: Build image
        run: docker build -t scramjetorg/runner-py:${{ inputs.git-revision }} -f Dockerfile ../../
        working-directory: packages/python-runner

      - name: Export image
        run: >
          docker images |
          awk '/scramjet/{print $1,$2,$3}' |
          sed 's|/| |' |
          while read repo name tag id; do
            docker save $repo/$name:$tag -o $repo-$name-$tag-docker-image.tar
          done

      - name: Zip exported images
        run: pigz *-docker-image.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v2
        with:
          name:  runner-python-image-${{ inputs.python-version }}.tar.gz
          path: '*.tar.gz'
          retention-days: 1
