name: Preinstall Dependencies

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        default: '16.x'
        type: string

jobs:
  build-sth:
    name: Install Dependencies ${{ inputs.node-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - name: Setup Nodejs ${{ inputs.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ inputs.node-version }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --ignore-engines --frozen-lockfile
