name: STH build and tests

on:
  pull_request:
    branches: [ release/*, main ]

jobs:
  build-test-sth:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Linter
        run: yarn lint

      - name: Build packages
        run: yarn build:packages

      - name: Build refapps
        run: yarn build:refapps

      - name: Pack sequences
        run: yarn packseq

      - name: Build Docker images
        run: yarn build:docker
      
      - name: Run packages tests
        run: yarn test:packages

      - name: Run BDD tests
        run: yarn test:bdd-ci
