name: Test STH - Main suite with Process Adapter

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        default: '18.x'
        type: string
      test-name:
        required: true
        type: string
      test-title:
        required: true
        type: string

jobs:
  test-bdd-sth:
    name: ${{ inputs.test-title }} (${{ inputs.test-name }}, Adapter "docker", Nodejs ${{ inputs.node-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - name: Download dist-sth-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-sth-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz

      - name: Download dist-refapps-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-refapps-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz

      - name: Install pigz
        run: sudo apt-get install pigz -y

      - name: Unzip dist-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz artifact
        run: ls dist*tar.gz |xargs -n1 tar -I pigz -xf

      - name: Setup Nodejs ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Inspect dist
        run: ls dist/ -la

      - name: Install dependencies
        run: yarn install --ignore-engines  --frozen-lockfile --prefer-offline --silent

      - name: Run BDD tests
        run: RUNTIME_ADAPTER=process SCRAMJET_TEST_LOG=1 SCRAMJET_SPAWN_JS=1 SCP_ENV_VALUE=GH_CI yarn ${{ inputs.test-name }} -t "not @not-github" -t "not @docker-specific"
        env:
          NODE_OPTIONS: "--trace-warnings"
