name: Test STH - Main suite with Process Adapter

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        default: '16.x'
        type: string

jobs:
  test-bdd-ci-sth-no-docker:
    name: Test STH - Main suite with Process Adapter (Nodejs ${{ inputs.node-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - name: Download dist-sth-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz artifact
        uses: actions/download-artifact@v2
        with:
          name: dist-sth-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz

      - name: Download reference apps (latest release)
        run: yarn download-refapps

      - name: Download dist-refapps-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz artifact
        uses: actions/download-artifact@v2
        with:
          name: dist-refapps-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz

      - name: Unzip dist-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz artifact
        run: ls dist*tar.gz |xargs -n1 tar -I pigz -xf

      - name: Setup Nodejs ${{ inputs.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: yarn install --ignore-engines  --frozen-lockfile --prefer-offline --silent

      - name: Run BDD tests
        run: SCRAMJET_TEST_LOG=1 yarn test:bdd-ci-no-docker
