name: Test STH - Unit tests

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        default: '18.x'
        type: string

jobs:
  test-bdd-ci-no-host-no-docker-sth:
    name: Test bdd-ci-no-host-no-docker STH (Nodejs ${{ inputs.node-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - name: Setup Nodejs ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download dist-sth-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-sth-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz

      - name: Install pigz
        run: sudo apt-get install pigz -y

      - name: Unzip dist-sth-${{ github.event.pull_request.head.sha }}-${{ inputs.node-version }}.tar.gz artifact
        run: ls dist*tar.gz |xargs -n1 tar -I pigz -xf

      - name: Install dependencies
        run: yarn install --ignore-engines  --frozen-lockfile --prefer-offline --silent

      - name: Run packages tests
        run: SCP_ENV_VALUE=GH_CI yarn test:packages-no-concurrent

